In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import csv
import os
import logging
import argparse
import random
from tqdm import tqdm, trange

import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from torch.utils.data.distributed import DistributedSampler

from pytorch_pretrained_bert.tokenization import BertTokenizer
from pytorch_pretrained_bert.modeling import BertForSequenceClassification
from pytorch_pretrained_bert.optimization import BertAdam
from pytorch_pretrained_bert.file_utils import PYTORCH_PRETRAINED_BERT_CACHE

logging.basicConfig(format = '%(asctime)s - %(levelname)s - %(name)s -   %(message)s',
                    datefmt = '%m/%d/%Y %H:%M:%S',
                    level = logging.INFO)
logger = logging.getLogger(__name__)

In [2]:
PYTORCH_PRETRAINED_BERT_CACHE

PosixPath('/Users/varunn/.pytorch_pretrained_bert')

In [3]:
class InputExample(object):
    """A single training/test example for simple sequence classification."""

    def __init__(self, guid, text_a, text_b=None, label=None):
        """Constructs a InputExample.
        Args:
            guid: Unique id for the example.
            text_a: string. The untokenized text of the first sequence. For single
            sequence tasks, only this sequence must be specified.
            text_b: (Optional) string. The untokenized text of the second sequence.
            Only must be specified for sequence pair tasks.
            label: (Optional) string. The label of the example. This should be
            specified for train and dev examples, but not for test examples.
        """
        self.guid = guid
        self.text_a = text_a
        self.text_b = text_b
        self.label = label

In [4]:
class InputFeatures(object):
    """A single set of features of data."""

    def __init__(self, input_ids, input_mask, segment_ids, label_id):
        self.input_ids = input_ids
        self.input_mask = input_mask
        self.segment_ids = segment_ids
        self.label_id = label_id

In [5]:
class DataProcessor(object):
    """Base class for data converters for sequence classification data sets."""

    def get_train_examples(self, data_dir):
        """Gets a collection of `InputExample`s for the train set."""
        raise NotImplementedError()

    def get_dev_examples(self, data_dir):
        """Gets a collection of `InputExample`s for the dev set."""
        raise NotImplementedError()

    def get_labels(self):
        """Gets the list of labels for this data set."""
        raise NotImplementedError()

    @classmethod
    def _read_tsv(cls, input_file, delimiter='\t', quotechar=None):
        """Reads a tab separated value file."""
        with open(input_file, "r", encoding='utf-8') as f:
            reader = csv.reader(f, delimiter=delimiter, quotechar=quotechar)
            lines = []
            for line in reader:
                lines.append(line)
            return lines

# Preparing MRPC dataset

In [7]:
!cabextract /Users/varunn/Documents/NLP-data/MRPC/MSRParaphraseCorpus.msi -d MRPC

Extracting cabinet: /Users/varunn/Documents/NLP-data/MRPC/MSRParaphraseCorpus.msi
  extracting MRPC/_2D65ED66D69C42A28B021C3E24C1D8C0
  extracting MRPC/_2DEC3DBE877E4DB192D17C0256E90F1D
  extracting MRPC/_63DE49D9E7214609BE7E38DD145D8081
  extracting MRPC/_B3CFEFE1C368459BA1D1B8A2FA07A16D
  extracting MRPC/_C5BC91AAB1554DF3AF5E4105DE57C85A
  extracting MRPC/_D18B15DC041F43D7925309EFFCFE0236
  extracting MRPC/_D7B391F9EAFF4B1B8BCE8F21B20B1B61

All done, no errors.


In [8]:
!cat MRPC/_2DEC3DBE877E4DB192D17C0256E90F1D | tr -d $'\r' > MRPC/msr_paraphrase_train.txt
!cat MRPC/_D7B391F9EAFF4B1B8BCE8F21B20B1B61 | tr -d $'\r' > MRPC/msr_paraphrase_test.txt

In [9]:
### not required
!rm MRPC/_*
!rm MRPC/MSRParaphraseCorpus.msi

rm: MRPC/_*: No such file or directory


In [9]:
count = 1
for line in open('MRPC/msr_paraphrase_test.txt'):
    if count <= 2:
        print(line)
    count += 1

Quality	#1 ID	#2 ID	#1 String	#2 String

1	1089874	1089925	PCCW's chief operating officer, Mike Butcher, and Alex Arena, the chief financial officer, will report directly to Mr So.	Current Chief Operating Officer Mike Butcher and Group Chief Financial Officer Alex Arena will report to So.



In [10]:
import urllib
import os
mrpc_dir = 'MRPC'
dev_mrpc_path = 'https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2Fmrpc_dev_ids.tsv?alt=media&token=ec5c0836-31d5-48f4-b431-7480817f1adc'
urllib.request.urlretrieve(dev_mrpc_path, os.path.join(mrpc_dir, "dev_ids.tsv"))

('MRPC/dev_ids.tsv', <http.client.HTTPMessage at 0x11d390208>)

In [11]:
import io
mrpc_train_file = 'MRPC/msr_paraphrase_train.txt'
mrpc_test_file = 'MRPC/msr_paraphrase_test.txt'
dev_ids = []
with io.open(os.path.join(mrpc_dir, "dev_ids.tsv"), encoding='utf-8') as ids_fh:
    for row in ids_fh:
        dev_ids.append(row.strip().split('\t'))
print('Train File')
with io.open(mrpc_train_file, encoding='utf-8') as data_fh, \
io.open(os.path.join(mrpc_dir, "train.tsv"), 'w', encoding='utf-8') as train_fh, \
io.open(os.path.join(mrpc_dir, "dev.tsv"), 'w', encoding='utf-8') as dev_fh:
    header = data_fh.readline()
    train_fh.write(header)
    dev_fh.write(header)
    for row in data_fh:
        label, id1, id2, s1, s2 = row.strip().split('\t')
        if [id1, id2] in dev_ids:
            dev_fh.write("%s\t%s\t%s\t%s\t%s\n" % (label, id1, id2, s1, s2))
        else:
            train_fh.write("%s\t%s\t%s\t%s\t%s\n" % (label, id1, id2, s1, s2))
print('Test File')
with io.open(mrpc_test_file, encoding='utf-8') as data_fh, \
io.open(os.path.join(mrpc_dir, "test.tsv"), 'w', encoding='utf-8') as test_fh:
    header = data_fh.readline()
    test_fh.write("index\t#1 ID\t#2 ID\t#1 String\t#2 String\n")
    for idx, row in enumerate(data_fh):
        label, id1, id2, s1, s2 = row.strip().split('\t')
        test_fh.write("%d\t%s\t%s\t%s\t%s\n" % (idx, id1, id2, s1, s2))

Train File
Test File


In [12]:
dp = DataProcessor._read_tsv('MRPC/dev.tsv')

In [13]:
dp[1]

['1',
 '1355540',
 '1355592',
 "He said the foodservice pie business doesn't fit the company's long-term growth strategy.",
 '"The foodservice pie business does not fit our long-term growth strategy.']

In [14]:
class MrpcProcessor(DataProcessor):
    """Processor for the MRPC data set (GLUE version)."""

    def get_train_examples(self, data_dir):
        """See base class."""
        logger.info("LOOKING AT {}".format(os.path.join(data_dir, "train.tsv")))
        return self._create_examples(
            self._read_tsv(os.path.join(data_dir, "train.tsv")), "train")

    def get_dev_examples(self, data_dir):
        """See base class."""
        return self._create_examples(
            self._read_tsv(os.path.join(data_dir, "dev.tsv")), "dev")

    def get_labels(self):
        """See base class."""
        return ["0", "1"]

    def _create_examples(self, lines, set_type):
        """Creates examples for the training and dev sets."""
        examples = []
        for (i, line) in enumerate(lines):
            if i == 0:
                continue
            guid = "%s-%s" % (set_type, i)
            text_a = line[3]
            text_b = line[4]
            label = line[0]
            examples.append(
                InputExample(guid=guid, text_a=text_a, text_b=text_b, label=label))
        return examples

In [15]:
def convert_examples_to_features(examples, label_list, max_seq_length, tokenizer):
    """Loads a data file into a list of `InputBatch`s."""

    label_map = {label : i for i, label in enumerate(label_list)}

    features = []
    for (ex_index, example) in enumerate(examples):
        tokens_a = tokenizer.tokenize(example.text_a)

        tokens_b = None
        if example.text_b:
            tokens_b = tokenizer.tokenize(example.text_b)
            # Modifies `tokens_a` and `tokens_b` in place so that the total
            # length is less than the specified length.
            # Account for [CLS], [SEP], [SEP] with "- 3"
            _truncate_seq_pair(tokens_a, tokens_b, max_seq_length - 3)
        else:
            # Account for [CLS] and [SEP] with "- 2"
            if len(tokens_a) > max_seq_length - 2:
                tokens_a = tokens_a[:(max_seq_length - 2)]

        # The convention in BERT is:
        # (a) For sequence pairs:
        #  tokens:   [CLS] is this jack ##son ##ville ? [SEP] no it is not . [SEP]
        #  type_ids: 0   0  0    0    0     0       0 0    1  1  1  1   1 1
        # (b) For single sequences:
        #  tokens:   [CLS] the dog is hairy . [SEP]
        #  type_ids: 0   0   0   0  0     0 0
        #
        # Where "type_ids" are used to indicate whether this is the first
        # sequence or the second sequence. The embedding vectors for `type=0` and
        # `type=1` were learned during pre-training and are added to the wordpiece
        # embedding vector (and position vector). This is not *strictly* necessary
        # since the [SEP] token unambigiously separates the sequences, but it makes
        # it easier for the model to learn the concept of sequences.
        #
        # For classification tasks, the first vector (corresponding to [CLS]) is
        # used as as the "sentence vector". Note that this only makes sense because
        # the entire model is fine-tuned.
        tokens = ["[CLS]"] + tokens_a + ["[SEP]"]
        segment_ids = [0] * len(tokens)

        if tokens_b:
            tokens += tokens_b + ["[SEP]"]
            segment_ids += [1] * (len(tokens_b) + 1)

        input_ids = tokenizer.convert_tokens_to_ids(tokens)

        # The mask has 1 for real tokens and 0 for padding tokens. Only real
        # tokens are attended to.
        input_mask = [1] * len(input_ids)

        # Zero-pad up to the sequence length.
        padding = [0] * (max_seq_length - len(input_ids))
        input_ids += padding
        input_mask += padding
        segment_ids += padding

        assert len(input_ids) == max_seq_length
        assert len(input_mask) == max_seq_length
        assert len(segment_ids) == max_seq_length

        label_id = label_map[example.label]
        if ex_index < 5:
            logger.info("*** Example ***")
            logger.info("guid: %s" % (example.guid))
            logger.info("tokens: %s" % " ".join(
                    [str(x) for x in tokens]))
            logger.info("input_ids: %s" % " ".join([str(x) for x in input_ids]))
            logger.info("input_mask: %s" % " ".join([str(x) for x in input_mask]))
            logger.info(
                    "segment_ids: %s" % " ".join([str(x) for x in segment_ids]))
            logger.info("label: %s (id = %d)" % (example.label, label_id))

        features.append(
                InputFeatures(input_ids=input_ids,
                              input_mask=input_mask,
                              segment_ids=segment_ids,
                              label_id=label_id))
    return features

In [16]:
def _truncate_seq_pair(tokens_a, tokens_b, max_length):
    """Truncates a sequence pair in place to the maximum length."""

    # This is a simple heuristic which will always truncate the longer sequence
    # one token at a time. This makes more sense than truncating an equal percent
    # of tokens from each, since if one sequence is very short then each token
    # that's truncated likely contains more information than a longer sequence.
    while True:
        total_length = len(tokens_a) + len(tokens_b)
        if total_length <= max_length:
            break
        if len(tokens_a) > len(tokens_b):
            tokens_a.pop()
        else:
            tokens_b.pop()

def accuracy(out, labels):
    outputs = np.argmax(out, axis=1)
    return np.sum(outputs == labels)

def warmup_linear(x, warmup=0.002):
    if x < warmup:
        return x/warmup
    return 1.0 - x

# training

In [17]:
data_dir = 'MRPC'
bert_model = 'bert-base-uncased'
task_name = 'mrpc'
output_dir = 'MRPC_Bert_Predictions'
max_seq_length = 128
do_train = True
do_eval = True
do_lower_case = True
train_batch_size = 32
eval_batch_size = 8
learning_rate = 5e-5
num_train_epochs = 3.0
warmup_proportion = 0.1
no_cuda = True
local_rank = -1
seed = 42
gradient_accumulation_steps = 1
fp16 = False
loss_scale = 0

processors = {
        "mrpc": MrpcProcessor,
    }

num_labels_task = {
    "cola": 2,
    "mnli": 3,
    "mrpc": 2,
}

In [18]:
if local_rank == -1 or no_cuda:
    device = torch.device("cuda" if torch.cuda.is_available() and not args.no_cuda else "cpu")
    n_gpu = torch.cuda.device_count()
else:
    torch.cuda.set_device(local_rank)
    device = torch.device("cuda", local_rank)
    n_gpu = 1
    # Initializes the distributed backend which will take care of sychronizing nodes/GPUs
    torch.distributed.init_process_group(backend='nccl')
logger.info("device: {} n_gpu: {}, distributed training: {}, 16-bits training: {}".format(
    device, n_gpu, bool(local_rank != -1), fp16))

04/02/2019 13:00:07 - INFO - __main__ -   device: cpu n_gpu: 0, distributed training: False, 16-bits training: False


In [19]:
device, '\t', n_gpu

(device(type='cpu'), '\t', 0)

In [20]:
if gradient_accumulation_steps < 1:
    raise ValueError("Invalid gradient_accumulation_steps parameter: {}, should be >= 1".format(
                     gradient_accumulation_steps))

In [21]:
train_batch_size = int(train_batch_size / gradient_accumulation_steps)

In [22]:
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
if n_gpu > 0:
    torch.cuda.manual_seed_all(seed)

if not do_train and not do_eval:
    raise ValueError("At least one of `do_train` or `do_eval` must be True.")

if os.path.exists(output_dir) and os.listdir(output_dir) and do_train:
    raise ValueError("Output directory ({}) already exists and is not empty.".format(args.output_dir))
os.makedirs(output_dir, exist_ok=True)

task_name = task_name.lower()

if task_name not in processors:
    raise ValueError("Task not found: %s" % (task_name))

processor = processors[task_name]()
num_labels = num_labels_task[task_name]
label_list = processor.get_labels()

In [23]:
tokenizer = BertTokenizer.from_pretrained(bert_model, do_lower_case=do_lower_case)

04/02/2019 13:00:14 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /Users/varunn/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084


In [24]:
train_examples = None
num_train_steps = None
if do_train:
    train_examples = processor.get_train_examples(data_dir)
    num_train_steps = int(
        len(train_examples) / train_batch_size / gradient_accumulation_steps * num_train_epochs)

04/02/2019 13:00:15 - INFO - __main__ -   LOOKING AT MRPC/train.tsv


In [25]:
len(train_examples), '\t', num_train_steps, '\t', train_batch_size, '\t', num_train_epochs

(3668, '\t', 343, '\t', 32, '\t', 3.0)

In [26]:
int(3668/32 * 3)

343

In [27]:
# Prepare model
model = BertForSequenceClassification.from_pretrained(bert_model,
          cache_dir=PYTORCH_PRETRAINED_BERT_CACHE / 'distributed_{}'.format(local_rank),
          num_labels = num_labels)
if fp16:
    model.half()
model.to(device)
if local_rank != -1:
    try:
        from apex.parallel import DistributedDataParallel as DDP
    except ImportError:
        raise ImportError("Please install apex from https://www.github.com/nvidia/apex to use distributed and fp16 training.")

    model = DDP(model)
elif n_gpu > 1:
    model = torch.nn.DataParallel(model)

04/02/2019 13:00:20 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /Users/varunn/.pytorch_pretrained_bert/distributed_-1/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
04/02/2019 13:00:20 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /Users/varunn/.pytorch_pretrained_bert/distributed_-1/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /var/folders/_y/2dty3nzx05zdf0lpd_r9bj1jbr9qbr/T/tmp3xej9ris
04/02/2019 13:00:25 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "

# Install Apex to use distributed and fp16 training

In [62]:
!git clone https://github.com/NVIDIA/apex.git

Cloning into 'apex'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 2580 (delta 58), reused 68 (delta 33), pack-reused 2467
Receiving objects: 100% (2580/2580), 7.94 MiB | 759.00 KiB/s, done.
Resolving deltas: 100% (1585/1585), done.


In [67]:
!pip3 install torch==0.4

  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/6c/41/5454da652b9cf75f4b5706ef71404352b6131484bb966f05c7899e6ac25d/torch-0.4.0-cp36-cp36m-macosx_10_7_x86_64.whl
    100% |████████████████████████████████| 8.2MB 1.9MB/s ta 0:00:011
pytorch-pretrained-bert 0.3.0 has requirement torch>=0.4.1, but you'll have torch 0.4.0 which is incompatible.
fastai 1.0.42 has requirement torch>=1.0.0, but you'll have torch 0.4.0 which is incompatible.
  Found existing installation: torch 1.0.0
    Uninstalling torch-1.0.0:
      Successfully uninstalled torch-1.0.0
You are using pip version 18.0, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
('Warning: Torch did not find available GPUs on this system.\n', 'If your intention is to cross-compile, this is 

In [28]:
# Prepare optimizer
param_optimizer = list(model.named_parameters())
no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in param_optimizer if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in param_optimizer if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
    ]
t_total = num_train_steps
if local_rank != -1:
    t_total = t_total // torch.distributed.get_world_size()
if fp16:
    try:
        from apex.optimizers import FP16_Optimizer
        from apex.optimizers import FusedAdam
    except ImportError:
        raise ImportError("Please install apex from https://www.github.com/nvidia/apex to use distributed and fp16 training.")

    optimizer = FusedAdam(optimizer_grouped_parameters,
                          lr=learning_rate,
                          bias_correction=False,
                          max_grad_norm=1.0)
    if loss_scale == 0:
        optimizer = FP16_Optimizer(optimizer, dynamic_loss_scale=True)
    else:
        optimizer = FP16_Optimizer(optimizer, static_loss_scale=loss_scale)

else:
    optimizer = BertAdam(optimizer_grouped_parameters,
                         lr=learning_rate,
                         warmup=warmup_proportion,
                         t_total=t_total)

In [29]:
train_features = convert_examples_to_features(
        train_examples, label_list, max_seq_length, tokenizer)

04/02/2019 13:00:43 - INFO - __main__ -   *** Example ***
04/02/2019 13:00:43 - INFO - __main__ -   guid: train-1
04/02/2019 13:00:43 - INFO - __main__ -   tokens: [CLS] am ##ro ##zi accused his brother , whom he called " the witness " , of deliberately di ##stor ##ting his evidence . [SEP] referring to him as only " the witness " , am ##ro ##zi accused his brother of deliberately di ##stor ##ting his evidence . [SEP]
04/02/2019 13:00:43 - INFO - __main__ -   input_ids: 101 2572 3217 5831 5496 2010 2567 1010 3183 2002 2170 1000 1996 7409 1000 1010 1997 9969 4487 23809 3436 2010 3350 1012 102 7727 2000 2032 2004 2069 1000 1996 7409 1000 1010 2572 3217 5831 5496 2010 2567 1997 9969 4487 23809 3436 2010 3350 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
04/02/2019 13:00:43 - INFO - __main__ -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

In [30]:
len(train_features)

3668

In [31]:
train_features[0].input_ids

[101,
 2572,
 3217,
 5831,
 5496,
 2010,
 2567,
 1010,
 3183,
 2002,
 2170,
 1000,
 1996,
 7409,
 1000,
 1010,
 1997,
 9969,
 4487,
 23809,
 3436,
 2010,
 3350,
 1012,
 102,
 7727,
 2000,
 2032,
 2004,
 2069,
 1000,
 1996,
 7409,
 1000,
 1010,
 2572,
 3217,
 5831,
 5496,
 2010,
 2567,
 1997,
 9969,
 4487,
 23809,
 3436,
 2010,
 3350,
 1012,
 102,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [32]:
all_input_ids = torch.tensor([f.input_ids for f in train_features], dtype=torch.long)
all_input_mask = torch.tensor([f.input_mask for f in train_features], dtype=torch.long)
all_segment_ids = torch.tensor([f.segment_ids for f in train_features], dtype=torch.long)
all_label_ids = torch.tensor([f.label_id for f in train_features], dtype=torch.long)

In [33]:
all_input_ids[0]

tensor([  101,  2572,  3217,  5831,  5496,  2010,  2567,  1010,  3183,  2002,
         2170,  1000,  1996,  7409,  1000,  1010,  1997,  9969,  4487, 23809,
         3436,  2010,  3350,  1012,   102,  7727,  2000,  2032,  2004,  2069,
         1000,  1996,  7409,  1000,  1010,  2572,  3217,  5831,  5496,  2010,
         2567,  1997,  9969,  4487, 23809,  3436,  2010,  3350,  1012,   102,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0])

In [34]:
train_data = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)

In [35]:
train_sampler = RandomSampler(train_data)

In [36]:
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=train_batch_size)

In [37]:
for batch in train_dataloader:
    batch = tuple(t.to(device) for t in batch)
    input_ids, input_mask, segment_ids, label_ids = batch
    print(input_ids)
    print(input_ids.size())
    break

tensor([[ 101, 2107, 1037,  ...,    0,    0,    0],
        [ 101, 2021, 2485,  ...,    0,    0,    0],
        [ 101, 2009, 2003,  ...,    0,    0,    0],
        ...,
        [ 101, 1037, 3764,  ...,    0,    0,    0],
        [ 101, 2002, 2056,  ...,    0,    0,    0],
        [ 101, 9530, 8490,  ...,    0,    0,    0]])
torch.Size([32, 128])


In [38]:
# training begins
global_step = 0
nb_tr_steps = 0
tr_loss = 0
if do_train:
    train_features = convert_examples_to_features(
        train_examples, label_list, max_seq_length, tokenizer)
    logger.info("***** Running training *****")
    logger.info("  Num examples = %d", len(train_examples))
    logger.info("  Batch size = %d", train_batch_size)
    logger.info("  Num steps = %d", num_train_steps)
    all_input_ids = torch.tensor([f.input_ids for f in train_features], dtype=torch.long)
    all_input_mask = torch.tensor([f.input_mask for f in train_features], dtype=torch.long)
    all_segment_ids = torch.tensor([f.segment_ids for f in train_features], dtype=torch.long)
    all_label_ids = torch.tensor([f.label_id for f in train_features], dtype=torch.long)
    train_data = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)
    if local_rank == -1:
        train_sampler = RandomSampler(train_data)
    else:
        train_sampler = DistributedSampler(train_data)
    train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=train_batch_size)

    model.train()
    for _ in trange(int(num_train_epochs), desc="Epoch"):
        tr_loss = 0
        nb_tr_examples, nb_tr_steps = 0, 0
        for step, batch in enumerate(tqdm(train_dataloader, desc="Iteration")):
            batch = tuple(t.to(device) for t in batch)
            input_ids, input_mask, segment_ids, label_ids = batch
            loss = model(input_ids, segment_ids, input_mask, label_ids)
            if n_gpu > 1:
                loss = loss.mean() # mean() to average on multi-gpu.
            if gradient_accumulation_steps > 1:
                loss = loss / gradient_accumulation_steps

            if fp16:
                optimizer.backward(loss)
            else:
                loss.backward()

            tr_loss += loss.item()
            nb_tr_examples += input_ids.size(0)
            nb_tr_steps += 1
            if (step + 1) % gradient_accumulation_steps == 0:
                # modify learning rate with special warm up BERT uses
                lr_this_step = learning_rate * warmup_linear(global_step/t_total, warmup_proportion)
                for param_group in optimizer.param_groups:
                    param_group['lr'] = lr_this_step
                optimizer.step()
                optimizer.zero_grad()
                global_step += 1

04/02/2019 13:01:18 - INFO - __main__ -   *** Example ***
04/02/2019 13:01:18 - INFO - __main__ -   guid: train-1
04/02/2019 13:01:18 - INFO - __main__ -   tokens: [CLS] am ##ro ##zi accused his brother , whom he called " the witness " , of deliberately di ##stor ##ting his evidence . [SEP] referring to him as only " the witness " , am ##ro ##zi accused his brother of deliberately di ##stor ##ting his evidence . [SEP]
04/02/2019 13:01:18 - INFO - __main__ -   input_ids: 101 2572 3217 5831 5496 2010 2567 1010 3183 2002 2170 1000 1996 7409 1000 1010 1997 9969 4487 23809 3436 2010 3350 1012 102 7727 2000 2032 2004 2069 1000 1996 7409 1000 1010 2572 3217 5831 5496 2010 2567 1997 9969 4487 23809 3436 2010 3350 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
04/02/2019 13:01:18 - INFO - __main__ -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

Iteration:  11%|█▏        | 13/115 [06:23<50:24, 29.65s/it]


Iteration:  23%|██▎       | 26/115 [13:53<47:20, 31.92s/it]


Epoch: 100%|██████████| 3/3 [2:58:01<00:00, 3537.35s/it]


In [39]:
# Save a trained model
model_to_save = model.module if hasattr(model, 'module') else model  # Only save the model it-self
output_model_file = os.path.join(output_dir, "pytorch_model.bin")
if do_train:
    torch.save(model_to_save.state_dict(), output_model_file)

In [40]:
# Load a trained model that you have fine-tuned
model_state_dict = torch.load(output_model_file, map_location=device)
model1 = BertForSequenceClassification.from_pretrained(bert_model, num_labels=num_labels)
model1.load_state_dict(model_state_dict)
model1.to(device)

04/02/2019 16:18:42 - INFO - pytorch_pretrained_bert.modeling -   loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /Users/varunn/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
04/02/2019 16:18:42 - INFO - pytorch_pretrained_bert.modeling -   extracting archive file /Users/varunn/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /var/folders/_y/2dty3nzx05zdf0lpd_r9bj1jbr9qbr/T/tmppphemfdg
04/02/2019 16:18:46 - INFO - pytorch_pretrained_bert.modeling -   Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "n

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): BertLayerNorm()
      (dropout): Dropout(p=0.1)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): BertLayerNorm()
              (dropout): Dropout(p=0.1)
            )
          )
          (intermediate): BertInterme

In [41]:
print(model.config)
print(model1.config)

{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}



In [42]:
if do_eval and (local_rank == -1 or torch.distributed.get_rank() == 0):
    eval_examples = processor.get_dev_examples(data_dir)
    eval_features = convert_examples_to_features(
        eval_examples, label_list, max_seq_length, tokenizer)
    logger.info("***** Running evaluation *****")
    logger.info("  Num examples = %d", len(eval_examples))
    logger.info("  Batch size = %d", eval_batch_size)
    all_input_ids = torch.tensor([f.input_ids for f in eval_features], dtype=torch.long)
    all_input_mask = torch.tensor([f.input_mask for f in eval_features], dtype=torch.long)
    all_segment_ids = torch.tensor([f.segment_ids for f in eval_features], dtype=torch.long)
    all_label_ids = torch.tensor([f.label_id for f in eval_features], dtype=torch.long)
    eval_data = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids)
    # Run prediction for full data
    eval_sampler = SequentialSampler(eval_data)
    eval_dataloader = DataLoader(eval_data, sampler=eval_sampler, batch_size=eval_batch_size)

    model.eval()
    eval_loss, eval_accuracy = 0, 0
    nb_eval_steps, nb_eval_examples = 0, 0

    for input_ids, input_mask, segment_ids, label_ids in tqdm(eval_dataloader, desc="Evaluating"):
        input_ids = input_ids.to(device)
        input_mask = input_mask.to(device)
        segment_ids = segment_ids.to(device)
        label_ids = label_ids.to(device)

        with torch.no_grad():
            tmp_eval_loss = model(input_ids, segment_ids, input_mask, label_ids)
            logits = model(input_ids, segment_ids, input_mask)
        print(logits)
        logits = logits.detach().cpu().numpy()
        label_ids = label_ids.to('cpu').numpy()
        tmp_eval_accuracy = accuracy(logits, label_ids)

        eval_loss += tmp_eval_loss.mean().item()
        eval_accuracy += tmp_eval_accuracy

        nb_eval_examples += input_ids.size(0)
        nb_eval_steps += 1

    eval_loss = eval_loss / nb_eval_steps
    eval_accuracy = eval_accuracy / nb_eval_examples
    loss = tr_loss/nb_tr_steps if do_train else None
    result = {'eval_loss': eval_loss,
              'eval_accuracy': eval_accuracy,
              'global_step': global_step,
              'loss': loss}

    output_eval_file = os.path.join(output_dir, "eval_results.txt")
    with open(output_eval_file, "w") as writer:
        logger.info("***** Eval results *****")
        for key in sorted(result.keys()):
            logger.info("  %s = %s", key, str(result[key]))
            writer.write("%s = %s\n" % (key, str(result[key])))

04/02/2019 16:19:42 - INFO - __main__ -   *** Example ***
04/02/2019 16:19:42 - INFO - __main__ -   guid: dev-1
04/02/2019 16:19:42 - INFO - __main__ -   tokens: [CLS] he said the foods ##er ##vic ##e pie business doesn ' t fit the company ' s long - term growth strategy . [SEP] " the foods ##er ##vic ##e pie business does not fit our long - term growth strategy . [SEP]
04/02/2019 16:19:42 - INFO - __main__ -   input_ids: 101 2002 2056 1996 9440 2121 7903 2063 11345 2449 2987 1005 1056 4906 1996 2194 1005 1055 2146 1011 2744 3930 5656 1012 102 1000 1996 9440 2121 7903 2063 11345 2449 2515 2025 4906 2256 2146 1011 2744 3930 5656 1012 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
04/02/2019 16:19:42 - INFO - __main__ -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

tensor([[-3.1818,  2.7929],
        [ 1.3366, -1.0892],
        [ 0.9410, -0.9200],
        [-2.9937,  2.3675],
        [ 1.3348, -1.0914],
        [-2.2992,  1.5050],
        [-1.2822,  0.4767],
        [-3.1211,  2.5602]])


Evaluating:   4%|▍         | 2/51 [00:09<03:59,  4.89s/it]

tensor([[-2.5136,  1.7666],
        [-2.7615,  2.0549],
        [-3.1807,  2.7941],
        [ 1.1995, -1.0859],
        [ 1.2775, -1.0279],
        [-3.1848,  2.6668],
        [-3.1569,  2.7890],
        [-2.3192,  1.5652]])


Evaluating:   6%|▌         | 3/51 [00:14<03:46,  4.71s/it]

tensor([[-3.2211,  2.7893],
        [ 1.2416, -1.0223],
        [-3.1625,  2.7746],
        [ 1.3238, -1.0293],
        [ 1.3748, -1.0547],
        [-1.9296,  1.0845],
        [ 1.3315, -1.0549],
        [-3.2023,  2.7855]])


Evaluating:   8%|▊         | 4/51 [00:18<03:31,  4.50s/it]

tensor([[-2.1205,  1.3320],
        [-1.7488,  0.9182],
        [-1.0321,  0.2851],
        [-3.1517,  2.7674],
        [-2.0852,  1.2828],
        [-3.0831,  2.4896],
        [-0.1843, -0.2877],
        [-3.1298,  2.7600]])


Evaluating:  10%|▉         | 5/51 [00:22<03:26,  4.50s/it]

tensor([[-2.0837,  1.2951],
        [-1.9656,  1.1345],
        [-3.2019,  2.7478],
        [-2.3388,  1.5938],
        [ 1.1030, -1.0202],
        [ 1.3979, -1.0844],
        [-3.1980,  2.7318],
        [-3.1456,  2.7712]])


Evaluating:  12%|█▏        | 6/51 [00:27<03:29,  4.65s/it]

tensor([[-0.4076, -0.1481],
        [-2.8235,  2.1746],
        [ 0.1338, -0.4460],
        [ 1.3643, -1.0839],
        [ 1.3143, -1.0564],
        [-3.2090,  2.7757],
        [-3.2254,  2.7678],
        [ 1.3299, -1.0902]])


Evaluating:  14%|█▎        | 7/51 [00:32<03:25,  4.66s/it]

tensor([[-3.2129,  2.7667],
        [-3.1985,  2.7089],
        [-2.3067,  1.5358],
        [-1.5383,  0.7170],
        [-3.0297,  2.3977],
        [-3.1982,  2.7742],
        [-2.9573,  2.3057],
        [-3.2050,  2.7270]])


Evaluating:  16%|█▌        | 8/51 [00:36<03:18,  4.62s/it]

tensor([[ 1.1743, -1.0269],
        [-3.2017,  2.7285],
        [-3.1944,  2.7932],
        [-3.0926,  2.4764],
        [-1.0581,  0.2911],
        [ 1.2766, -1.0675],
        [-3.1875,  2.6808],
        [-2.7346,  2.0415]])


Evaluating:  18%|█▊        | 9/51 [00:41<03:09,  4.51s/it]

tensor([[-3.0669,  2.5105],
        [ 1.3140, -1.0426],
        [-3.1558,  2.7663],
        [-3.1909,  2.7767],
        [-1.9124,  1.0681],
        [-3.2033,  2.7411],
        [-3.2060,  2.7892],
        [ 0.8407, -0.8689]])


Evaluating:  20%|█▉        | 10/51 [00:45<02:59,  4.38s/it]

tensor([[-3.2109,  2.8005],
        [-2.1449,  1.3296],
        [-2.8536,  2.1929],
        [-1.5405,  0.6902],
        [-3.0333,  2.3964],
        [-3.1767,  2.7695],
        [-3.2149,  2.7159],
        [-3.0994,  2.5121]])


Evaluating:  22%|██▏       | 11/51 [00:49<02:56,  4.42s/it]

tensor([[-1.5099,  0.6397],
        [-1.9535,  1.1056],
        [-3.1567,  2.7229],
        [-0.7058,  0.0464],
        [-3.1954,  2.7818],
        [-0.9743,  0.1974],
        [-3.0007,  2.3635],
        [-1.2765,  0.4788]])


Evaluating:  24%|██▎       | 12/51 [00:54<02:53,  4.46s/it]

tensor([[-3.1968,  2.7983],
        [-3.1400,  2.7710],
        [-0.1323, -0.3073],
        [-3.2106,  2.7798],
        [-3.0609,  2.4845],
        [-2.7962,  2.0339],
        [-3.0390,  2.4558],
        [-3.1879,  2.7819]])


Evaluating:  25%|██▌       | 13/51 [00:59<02:54,  4.58s/it]

tensor([[ 1.0179, -0.9779],
        [-3.0278,  2.3962],
        [-3.0475,  2.4421],
        [-2.5764,  1.8436],
        [-3.1079,  2.5155],
        [-0.8198,  0.1153],
        [-2.2475,  1.4614],
        [-3.2229,  2.7572]])


Evaluating:  27%|██▋       | 14/51 [01:03<02:45,  4.48s/it]

tensor([[ 0.3043, -0.5447],
        [-3.1994,  2.7313],
        [-1.8163,  0.9421],
        [ 1.3918, -1.0574],
        [ 1.1817, -1.0261],
        [-3.1716,  2.6331],
        [ 0.3933, -0.6101],
        [-3.1454,  2.5975]])


Evaluating:  29%|██▉       | 15/51 [01:07<02:41,  4.48s/it]

tensor([[-2.4248,  1.7043],
        [-3.1404,  2.7663],
        [ 0.1137, -0.4335],
        [ 1.2449, -1.0316],
        [-2.8445,  2.1942],
        [-3.1880,  2.7827],
        [-3.1856,  2.7871],
        [-3.1935,  2.7730]])


Evaluating:  31%|███▏      | 16/51 [01:12<02:40,  4.59s/it]

tensor([[-3.2100,  2.6788],
        [-1.2290,  0.4393],
        [ 1.3714, -1.0560],
        [-3.1639,  2.6606],
        [-3.1450,  2.6107],
        [-3.2163,  2.7279],
        [-3.0142,  2.3958],
        [ 1.3420, -1.0953]])


Evaluating:  33%|███▎      | 17/51 [01:17<02:36,  4.60s/it]

tensor([[-3.1783,  2.7930],
        [-2.5962,  1.8597],
        [-1.9497,  1.1282],
        [ 1.1526, -1.0123],
        [-3.0561,  2.4247],
        [-0.0360, -0.3656],
        [-1.7644,  0.9708],
        [-1.4805,  0.6539]])


Evaluating:  35%|███▌      | 18/51 [01:22<02:37,  4.77s/it]

tensor([[-2.5021,  1.7792],
        [ 1.2467, -1.0385],
        [-3.1753,  2.7889],
        [-2.9068,  2.2818],
        [-3.1693,  2.6497],
        [ 0.1489, -0.4795],
        [ 1.3980, -1.0752],
        [-3.1631,  2.6243]])


Evaluating:  37%|███▋      | 19/51 [01:27<02:35,  4.87s/it]

tensor([[ 1.3493, -1.0718],
        [-0.0705, -0.3544],
        [-3.2117,  2.7914],
        [-0.8289,  0.1991],
        [ 0.4038, -0.6140],
        [-1.6331,  0.7842],
        [ 1.3563, -1.0830],
        [-2.4526,  1.7108]])


Evaluating:  39%|███▉      | 20/51 [01:31<02:25,  4.70s/it]

tensor([[-1.9536,  1.1252],
        [-3.2088,  2.7216],
        [-1.3331,  0.5007],
        [-3.0982,  2.5204],
        [-3.1132,  2.5583],
        [-2.5822,  1.8298],
        [ 0.9970, -0.9455],
        [-2.0234,  1.2269]])


Evaluating:  41%|████      | 21/51 [01:36<02:18,  4.63s/it]

tensor([[-2.7242,  2.0196],
        [-2.9499,  2.2998],
        [-3.1997,  2.7970],
        [-3.1317,  2.7522],
        [-3.2071,  2.7130],
        [-3.1903,  2.7440],
        [-1.5830,  0.7405],
        [ 0.2505, -0.5091]])


Evaluating:  43%|████▎     | 22/51 [01:40<02:11,  4.55s/it]

tensor([[-1.4642,  0.6133],
        [ 1.1757, -1.0473],
        [ 0.3019, -0.5543],
        [-1.6345,  0.7953],
        [-0.9621,  0.2114],
        [-2.9112,  2.2258],
        [-1.0607,  0.2863],
        [-1.0961,  0.3208]])


Evaluating:  45%|████▌     | 23/51 [01:44<02:04,  4.44s/it]

tensor([[-1.8694,  1.0229],
        [ 0.7884, -0.8344],
        [-3.1739,  2.7778],
        [-2.8865,  2.2046],
        [-1.6830,  0.8193],
        [-2.3050,  1.5067],
        [-2.5492,  1.7894],
        [-3.1890,  2.7614]])


Evaluating:  47%|████▋     | 24/51 [01:49<01:58,  4.38s/it]

tensor([[-1.4889,  0.6661],
        [-2.4364,  1.6658],
        [ 1.3435, -1.0801],
        [-0.9731,  0.2438],
        [ 1.3693, -1.0814],
        [-2.3653,  1.6406],
        [-3.2158,  2.7622],
        [ 1.3600, -1.0969]])


Evaluating:  49%|████▉     | 25/51 [01:53<01:54,  4.41s/it]

tensor([[-0.5511, -0.0622],
        [-3.1615,  2.7676],
        [-1.4607,  0.6183],
        [-2.1695,  1.3731],
        [-3.1919,  2.7752],
        [ 0.4148, -0.6010],
        [-2.5478,  1.8654],
        [-2.0784,  1.2436]])


Evaluating:  51%|█████     | 26/51 [01:58<01:57,  4.72s/it]

tensor([[-2.1308,  1.3970],
        [-1.5608,  0.7371],
        [ 1.3607, -1.0632],
        [-2.5188,  1.7784],
        [-1.6605,  0.8169],
        [ 1.3465, -1.0766],
        [-3.1250,  2.6092],
        [-2.1401,  1.3606]])


Evaluating:  53%|█████▎    | 27/51 [02:03<01:52,  4.68s/it]

tensor([[-0.7743,  0.0793],
        [ 0.8036, -0.8407],
        [ 0.8722, -0.8987],
        [-3.1756,  2.6570],
        [-0.7237,  0.0412],
        [ 1.3261, -1.0507],
        [-3.0141,  2.4124],
        [-3.1564,  2.7652]])


Evaluating:  55%|█████▍    | 28/51 [02:08<01:47,  4.66s/it]

tensor([[-1.7211,  0.8675],
        [-2.9397,  2.2926],
        [ 1.2882, -1.0855],
        [-3.0499,  2.4557],
        [-2.2374,  1.4764],
        [-2.9414,  2.3583],
        [-3.1988,  2.6888],
        [ 1.3338, -1.0734]])


Evaluating:  57%|█████▋    | 29/51 [02:12<01:42,  4.68s/it]

tensor([[-3.1733,  2.7753],
        [-3.1840,  2.7741],
        [-3.1533,  2.7741],
        [-1.5058,  0.5978],
        [-1.9600,  1.1219],
        [-1.9383,  1.1369],
        [-2.8081,  2.1412],
        [-2.3521,  1.6039]])


Evaluating:  59%|█████▉    | 30/51 [02:17<01:34,  4.52s/it]

tensor([[-4.2722e-01, -1.3810e-01],
        [-4.5669e-01, -1.2393e-01],
        [-8.2717e-01,  1.2975e-01],
        [-6.6382e-01,  1.1546e-03],
        [-1.3805e+00,  5.2609e-01],
        [ 1.0202e+00, -9.7470e-01],
        [-2.0344e+00,  1.2020e+00],
        [-1.5958e-01, -2.9451e-01]])


Evaluating:  61%|██████    | 31/51 [02:21<01:28,  4.41s/it]

tensor([[-3.0668,  2.5262],
        [ 1.3566, -1.0945],
        [ 0.3718, -0.5925],
        [-2.5327,  1.8166],
        [-2.3661,  1.6811],
        [-1.9523,  1.1035],
        [-2.7422,  2.0217],
        [-2.0635,  1.2453]])


Evaluating:  63%|██████▎   | 32/51 [02:25<01:23,  4.41s/it]

tensor([[-2.8425,  2.1759],
        [-2.9399,  2.3148],
        [-2.6125,  1.8908],
        [ 0.6652, -0.7683],
        [ 0.0450, -0.4019],
        [-1.5507,  0.7113],
        [ 1.1428, -1.0135],
        [ 1.4285, -1.0767]])


Evaluating:  65%|██████▍   | 33/51 [02:29<01:18,  4.37s/it]

tensor([[-2.2875,  1.5203],
        [-2.5832,  1.8941],
        [-2.2116,  1.4114],
        [-0.4674, -0.0959],
        [-1.9173,  1.1143],
        [-3.0804,  2.4971],
        [-2.7803,  2.0696],
        [-1.3149,  0.5095]])


Evaluating:  67%|██████▋   | 34/51 [02:34<01:13,  4.34s/it]

tensor([[-2.5956,  1.7718],
        [-0.7749,  0.0955],
        [ 0.8500, -0.8538],
        [ 0.2823, -0.5431],
        [ 1.3724, -1.0500],
        [-2.3651,  1.5904],
        [ 0.9246, -0.9213],
        [-2.6482,  1.9284]])


Evaluating:  69%|██████▊   | 35/51 [02:38<01:11,  4.48s/it]

tensor([[-3.1331,  2.5524],
        [-3.1872,  2.7934],
        [-3.1479,  2.7084],
        [-3.1832,  2.7086],
        [-3.1866,  2.7022],
        [-0.6897,  0.0250],
        [-2.6012,  1.8670],
        [ 1.3289, -1.0675]])


Evaluating:  71%|███████   | 36/51 [02:43<01:06,  4.46s/it]

tensor([[-2.1308,  1.3318],
        [-0.8877,  0.1763],
        [-2.1823,  1.4274],
        [ 1.3378, -1.0816],
        [ 0.2745, -0.5069],
        [-3.1980,  2.7238],
        [-2.7059,  1.9726],
        [-2.1275,  1.3332]])


Evaluating:  73%|███████▎  | 37/51 [02:48<01:03,  4.56s/it]

tensor([[-3.2078,  2.7776],
        [ 1.2104, -1.0308],
        [ 0.4212, -0.6100],
        [ 1.2925, -1.0791],
        [-3.1951,  2.7925],
        [-2.0279,  1.2188],
        [-2.7700,  2.0845],
        [ 0.9598, -0.9308]])


Evaluating:  75%|███████▍  | 38/51 [02:53<01:00,  4.68s/it]

tensor([[ 1.3588, -1.0907],
        [-1.1043,  0.3275],
        [-3.1665,  2.7765],
        [-1.3034,  0.5314],
        [-3.1491,  2.7707],
        [-3.1922,  2.6970],
        [-3.0859,  2.5194],
        [ 0.9119, -0.8955]])


Evaluating:  76%|███████▋  | 39/51 [02:57<00:53,  4.48s/it]

tensor([[-3.1945,  2.7872],
        [-3.1947,  2.7113],
        [ 1.4139, -1.0936],
        [-3.2007,  2.7759],
        [ 1.3869, -1.0983],
        [-0.9958,  0.2351],
        [-3.0112,  2.3651],
        [-3.2038,  2.7998]])


Evaluating:  78%|███████▊  | 40/51 [03:01<00:48,  4.37s/it]

tensor([[-1.2421,  0.4883],
        [ 1.2034, -1.0511],
        [-3.1963,  2.7828],
        [ 0.9999, -0.9657],
        [-1.2790,  0.4466],
        [-3.1735,  2.6451],
        [ 1.2365, -1.0549],
        [ 0.5568, -0.7051]])


Evaluating:  80%|████████  | 41/51 [03:05<00:43,  4.34s/it]

tensor([[ 1.3423, -1.0910],
        [ 1.2792, -1.0619],
        [ 1.2771, -1.0361],
        [-2.0934,  1.3338],
        [ 0.5900, -0.7255],
        [-3.1457,  2.7758],
        [-2.3611,  1.6411],
        [-3.2081,  2.7919]])


Evaluating:  82%|████████▏ | 42/51 [03:09<00:38,  4.31s/it]

tensor([[-2.6679,  1.9419],
        [-1.9656,  1.1518],
        [-3.1301,  2.5764],
        [-3.1795,  2.6576],
        [-1.4228,  0.5777],
        [-2.1648,  1.3741],
        [-3.1820,  2.7828],
        [-3.0221,  2.4067]])


Evaluating:  84%|████████▍ | 43/51 [03:13<00:34,  4.27s/it]

tensor([[-3.2143,  2.7632],
        [-2.9056,  2.2608],
        [ 1.3182, -1.0793],
        [-2.1765,  1.4223],
        [-3.1154,  2.5835],
        [-3.1728,  2.7677],
        [ 1.3403, -1.0925],
        [-0.5491, -0.0611]])


Evaluating:  86%|████████▋ | 44/51 [03:18<00:30,  4.32s/it]

tensor([[-3.2153,  2.7373],
        [-3.2096,  2.7976],
        [-3.2036,  2.7591],
        [-3.2162,  2.7959],
        [-0.9563,  0.2273],
        [-3.2012,  2.7447],
        [ 1.1923, -1.0526],
        [-3.1991,  2.7564]])


Evaluating:  88%|████████▊ | 45/51 [03:23<00:26,  4.50s/it]

tensor([[-2.2668,  1.4232],
        [-2.3256,  1.5842],
        [-2.7625,  2.0707],
        [ 1.3068, -1.0516],
        [-2.4183,  1.6585],
        [-2.5501,  1.8183],
        [-2.9358,  2.3314],
        [-2.3695,  1.6170]])


Evaluating:  90%|█████████ | 46/51 [03:27<00:22,  4.51s/it]

tensor([[ 0.9610, -0.9278],
        [-2.9314,  2.2895],
        [-3.1449,  2.7668],
        [-1.8638,  1.0022],
        [-2.7574,  2.0107],
        [-3.2009,  2.7993],
        [-3.1954,  2.7033],
        [-1.6754,  0.8472]])


Evaluating:  92%|█████████▏| 47/51 [03:32<00:18,  4.53s/it]

tensor([[ 1.1476, -1.0601],
        [ 1.3759, -1.0547],
        [-0.9250,  0.1878],
        [-3.1579,  2.6812],
        [-2.6467,  1.9231],
        [ 0.1745, -0.5052],
        [ 1.3546, -1.0861],
        [ 1.0821, -1.0020]])


Evaluating:  94%|█████████▍| 48/51 [03:36<00:13,  4.49s/it]

tensor([[ 0.3477, -0.5600],
        [ 1.4137, -1.0883],
        [-2.0451,  1.2514],
        [-3.2081,  2.7173],
        [-1.8683,  1.0134],
        [-3.1964,  2.8001],
        [-0.3271, -0.2212],
        [-3.1510,  2.7615]])


Evaluating:  96%|█████████▌| 49/51 [03:41<00:09,  4.63s/it]

tensor([[-2.9890,  2.3864],
        [-0.3441, -0.1820],
        [-2.5237,  1.7909],
        [ 1.1096, -1.0121],
        [-3.1888,  2.7937],
        [-0.7072,  0.0301],
        [-3.1906,  2.6910],
        [-0.7787,  0.1050]])


Evaluating:  98%|█████████▊| 50/51 [03:46<00:04,  4.58s/it]

tensor([[-3.2151,  2.7859],
        [-3.1834,  2.6645],
        [-2.0960,  1.2165],
        [-0.1442, -0.2922],
        [-3.2159,  2.7947],
        [-0.9473,  0.2199],
        [-2.5020,  1.7557],
        [-3.1770,  2.6475]])


Evaluating: 100%|██████████| 51/51 [03:51<00:00,  4.68s/it]
04/02/2019 16:23:33 - INFO - __main__ -   ***** Eval results *****
04/02/2019 16:23:33 - INFO - __main__ -     eval_accuracy = 0.8602941176470589
04/02/2019 16:23:33 - INFO - __main__ -     eval_loss = 0.415484676977583
04/02/2019 16:23:33 - INFO - __main__ -     global_step = 345
04/02/2019 16:23:33 - INFO - __main__ -     loss = 0.18990675794041675


tensor([[ 1.3128, -1.0338],
        [-3.2089,  2.7509],
        [-1.9044,  1.0529],
        [ 1.4479, -1.0434],
        [ 0.1515, -0.4591],
        [-3.1568,  2.7844],
        [ 1.2631, -1.0399],
        [-2.4895,  1.8019]])


In [43]:
result

{'eval_loss': 0.415484676977583,
 'eval_accuracy': 0.8602941176470589,
 'global_step': 345,
 'loss': 0.18990675794041675}