In [1]:
from __future__ import print_function
import os
import numpy as np
import random
import string
import tensorflow as tf
import zipfile
from six.moves import range
from six.moves.urllib.request import urlretrieve

/Users/varunn/.virtualenvs/xgb/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
help(urlretrieve)

Help on function urlretrieve in module urllib:

urlretrieve(url, filename=None, reporthook=None, data=None, context=None)



In [3]:
url = 'http://mattmahoney.net/dc/'
data_path = '/Users/varunn/Documents/NLP-data/'

def maybe_download(filename, expected_bytes):
    if not os.path.exists(data_path+filename):
        filename, _ = urlretrieve(url+filename, filename)
    statinfo = os.stat(filename)
    if statinfo.st_size == expected_bytes:
        print('Found and verified %s' % filename)
    else:
        print(statinfo.st_size)
        raise Exception(
          'Failed to verify ' + filename + '. Can you get to it with a browser?')
    return filename

filename = maybe_download('text8.zip', 31344016)

Found and verified text8.zip


In [4]:
# save filename to data_path
zip_file = zipfile.ZipFile(data_path+'text8.zip', "w")
zip_file.write(filename)
zip_file.close()

In [5]:
def read_data(filename):
    with zipfile.ZipFile(filename) as f:
        name = f.namelist()[0]
        data = tf.compat.as_str(f.read(name))
    return data

text = read_data(filename)
print('Data size: %d' % len(text))

Data size: 100000000


In [11]:
valid_size = 1000
valid_text = text[:valid_size]
train_text = text[valid_size:]
train_size = len(train_text)
print(train_size, train_text[:64])
print(valid_size, valid_text[:64])

99999000 ons anarchists advocate social relations based upon voluntary as
1000  anarchism originated as a term of abuse first used against earl


In [13]:
vocabulary_size = len(string.ascii_lowercase) + 2
first_letter = ord(string.ascii_lowercase[0])

In [18]:
print(ord('b'))
print(chr(98))

98
b


In [19]:
def char2id(char):
    if char in string.ascii_lowercase:
        return ord(char) - first_letter + 2
    elif char == ' ':
        return 1
    elif char == '#':
        return 0
    else:
        print('Unexpected character: %s' % char)
        return 0

def id2char(dictid):
    if dictid > 1:
        return chr(dictid + first_letter - 2)
    elif dictid == 1:
        return ' '
    elif dictid == 0:
        return '#'

In [20]:
print(char2id('a'), char2id('z'), char2id(' '), char2id('ï'))
print(id2char(1), id2char(26), id2char(0))

Unexpected character: ï
2 27 1 0
  y #


In [21]:
def reverse(alist):
    new_list = []
    for i in range(1, len(alist)+1):
        new_list.append(alist[-i])
    return new_list

In [22]:
vocabulary_size

28

In [24]:
batch = np.zeros(shape=(64, vocabulary_size), dtype=np.float)
print(batch.shape)
print(batch)

(64, 28)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
